version: '3.9'

services:
  db:
    image: postgres:14
    container_name: db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=kotai
    - POSTGRES_PASSWORD=kotai
    - POSTGRES_DB=patient

