version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=kotai
    - POSTGRES_PASSWORD=kotai
    - POSTGRES_DB=kotai

  # kotai:
  #   image: docker.io/adhondt42/server:latest
  #   container_name: kotai
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=kotai
  #     - DB_PASSWORD=kotai
  #     - DB_NAME=kotai
  #     - PORT=8080
